# Generated by Django 4.2.11 on 2024-04-16 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkout', '0001_initial'),
        ('products', '0008_personalisedproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPersonalised',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('original_bag', models.TextField(default='')),
                ('stripe_pid', models.CharField(default='', max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('size', models.CharField(choices=[('A4', 'A4'), ('A5', 'A5'), ('A6', 'A6')], default='A4', max_length=2)),
                ('paper', models.CharField(choices=[('Textured', 'Textured'), ('Smooth', 'Smooth'), ('Tan', 'Tan'), ('Black', 'Black')], default='Textured', max_length=10)),
                ('frame', models.CharField(choices=[('No frame', 'No frame'), ('White', 'White'), ('Black', 'Black'), ('Brown', 'Brown')], default='No frame', max_length=10)),
                ('subject', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='Subject 1', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalisedOrderLineItem',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='checkout.order')),
                ('personalised_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.personalisedproduct')),
            ],
        ),
    ]
