# Generated by Django 4.2.11 on 2024-04-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalised', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderPersonalised',
        ),
        migrations.DeleteModel(
            name='PersonalisedOrderLineItem',
        ),
    ]
