# Generated by Django 4.2.11 on 2024-04-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personalised', '0002_delete_orderpersonalised_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personalised',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('name', models.CharField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('size', models.CharField(choices=[('A4', 'A4 - 21.0 x 29.7 cm'), ('A5', 'A5 - 14.8 x 21.0 cm'), ('A6', 'A6 - 10.5 x 14.8 cm')], default='A4', max_length=2)),
                ('orientation', models.BooleanField(choices=[(True, 'Portrait'), (False, 'Landscape')], default=True)),
                ('brushes', models.CharField(choices=[('pen', 'Pen'), ('watery_brush', 'Watery Brush'), ('chalk', 'Chalk'), ('pencil', 'Pencil')], default='pen', max_length=12)),
                ('colours', models.BooleanField(choices=[(True, 'Coloured'), (False, 'Black & White')], default=True)),
            ],
        ),
    ]
