# Generated by Django 4.2.11 on 2024-04-29 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_delete_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='save',
        ),
    ]
