# Generated by Django 4.2.11 on 2024-04-29 12:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_remove_event_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='save_event',
            field=models.ManyToManyField(related_name='saved_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
