# Generated by Django 3.2.25 on 2024-04-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20240408_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Surface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='producttags',
            name='frame',
            field=models.ManyToManyField(to='products.Frame'),
        ),
        migrations.AddField(
            model_name='producttags',
            name='paint',
            field=models.ManyToManyField(to='products.Paint'),
        ),
        migrations.AddField(
            model_name='producttags',
            name='paper',
            field=models.ManyToManyField(to='products.Paper'),
        ),
        migrations.AddField(
            model_name='producttags',
            name='surface',
            field=models.ManyToManyField(to='products.Surface'),
        ),
    ]
