# Generated by Django 3.2.25 on 2024-04-08 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_producttags_digital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttags',
            name='digital',
        ),
    ]
