# Generated by Django 4.2.11 on 2024-04-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offers',
            field=models.BooleanField(default=False),
        ),
    ]
