# Generated by Django 4.2.11 on 2024-04-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_bundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='offers',
            field=models.BooleanField(default=True),
        ),
    ]
