# Generated by Django 4.2.11 on 2024-04-29 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_bundle_offers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bundle',
        ),
    ]
